version: "3"
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mqtt
