name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install black ruff pytest
      - name: Black check
        run: black --check .
      - name: Ruff lint
        run: ruff check .
      - name: Pytest
        run: pytest
      - name: Pytest coverage check (placeholder)
        run: echo "TODO: enforce coverage thresholds"
  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Jest
        run: npm test --if-present
      - name: Jest coverage check (placeholder)
        run: echo "TODO: enforce coverage thresholds"
